fix: 그룹이 없는 경우 프로필 수정이 불가한 문제
snack-game/front pull request #289
Opened 2024-08-13 06:45 UTC by nijuy

## 💻 개요

- 이슈대응
- #288

## 📋 변경 및 추가 사항

### 입력한 그룹 값이 없는데 에러 메시지가 왜 뜨냐

1. 그룹이 없는 경우 서버 응답의 `group` = null ➡️ 이는 `newGroup.value = ''`으로 초기화
2. 공백은 `GROUP_CHANGE_REGEXP` 정규식에 어긋나 invalid한 값으로 판단

    ![image](https://github.com/user-attachments/assets/0e8b51f0-6624-46cc-bf90-bc86f84ad163)

### 를 이렇게 수정했습니다

1. 그룹이 공백인 경우 정규식을 거치지 않고 valid한 값으로 판단하도록 합니다 (ProfileSection.tsx / 라인 47)
2. 그룹 수정 API 요청을 보내는 조건에 `공백이 아닐 경우`를 추가합니다 (ProfileSection.tsx / 라인 70)

![profile](https://github.com/user-attachments/assets/67caa585-27d3-4be8-874c-170b5abb96a1)

> 💫 닉네임만 바꿨을 때 프로필 수정이 가능한 점 -> 이후 그룹 설정도 되는 점에 집중해서 봐주시면 됩니다!!

## 💬 To. 리뷰어

그근데
한번 그룹에 가입하면 탈퇴는 안되는 거네요...?!
나중에 그룹 이름을 공백으로 보내면 탈퇴 처리한다 ⬅️ 요런 기능도 계획에 있나요??

2024-08-13 06:49 UTC, nijuy commented on src/pages/user/components/ProfileSection.tsx
> +    isInvalid: (group) => (group ? GROUP_CHANGE_REGEXP.test(group) : true),
> 그룹이 공백인 경우 정규식을 거치지 않고 **valid한 값으로 판단**하도록 합니다

근데 `isInvalid = true`면 valid하지 않은 값으로 판단하는 거.. 아닐까?! 라는 궁금증이 혹시 생기실까봐....

```tsx
// useInput
const [valid, setValid] = useState<boolean>(isInvalid ? isInvalid(initialValue) : true,);
```

`isInvalid`가 있는 경우 그 결과가 `vaild` 상태의 초기 값입니다
`isInvalid(value) = true = valid한 값`이라고 보시면 될 거 같아요

PR 올리고보니까 약간,, 이름이 혼동을 주는 거 같아 `isValid`로 수정하려고 합니다........!

2024-08-13 06:59 UTC, 0chil commented
제가 밖이라 그룹 먼저 답변드리고 리뷰는 나중에 할게요!
그룹 탈퇴는 로직상으로는 가능한데 api 상으로는 안되네요 ㅠㅠ
오늘밤에 수정할테니 공백이 아닌 null(없음)
으로 표현해주시면 감사드리겠습니다.

2024-08-13 07:57 UTC, nijuy commented on src/hooks/queries/members.query.ts
## 문제 상황

1. `/user` 접속 시 서버에서 프로필 정보를 받아옴 (이하 `profile`)

2. `profile`을 `EditInfo` 컴포넌트로 전달해서, 프로필 수정 시 기본값으로 사용함

3. 계정을 바꿔서 로그인 했을 때, **이전 `profile`이 노출되는 경우가 존재**
  
    - `계정 1 로그아웃` ➡️ `계정 2 로그인` ➡️ `계정 2 프로필 수정`에서 `계정 1 profile`이 노출

## 원인 & 수정

1. 서버에서 받아온 `profile`은 일정 시간동안 캐시됨

2. 계정을 바꿔서 로그인할 경우, 캐시된 `profile`이 `EditInfo`로 전달되는 경우가 있음

    - 캐시 데이터가 존재하지 않도록 `gcTime`을 0으로 수정 (default 5분이었음)

## 수정 전후 비교

| before | after |
|:---:|:---:|
|![beforeprofile](https://github.com/user-attachments/assets/6cbbe39d-decc-470b-9120-8b693b514be7)|![afterprofile](https://github.com/user-attachments/assets/fd52ecf5-30aa-4641-95ad-d47e940f2e62)|
|`매우깨끗한snack`에서 프로필 수정할 때 닉네임이 `어정쩡고라니`인 문제||

2024-08-13 12:13 UTC, nijuy commented on src/pages/user/components/ProfileSection.tsx
> +      newProfile = await changeGroupName.mutateAsync(newGroup.value || null);
## 그룹 탈퇴

- `a || b` 꼴에서 a가 falsy한 값일 경우 b가 반환됩니다.
- 공백 문자열 `''`은 falsy한 값이므로, `'' || null = null` 입니다.
- `newGroup.value`는 길이 0 이상의 string임이 보장됩니다

    ```ts
      const newGroup = useInput<string>({
        initialValue: profile.group?.name || '',
      });
    ```

2024-08-14 05:54 UTC, 0chil requested changes

2024-08-14 05:54 UTC, 0chil commented on src/pages/user/components/ProfileSection.tsx
> +      newProfile = await changeGroupName.mutateAsync(newGroup.value || null);
or 연산자를 활용해주셨네요. null과 ''를 구분하는 방법 중 아직까진 가장 괜찮은 방법 같습니다 👍
<img width="698" alt="image" src="https://github.com/user-attachments/assets/e4a7c090-f601-4a22-b9c0-633d73b1c160">
서버에서도 같은 제약조건을 사용하도록 수정했으니 확인 부탁드립니다!

2024-08-14 05:54 UTC, 0chil commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
https://github.com/snack-game/front/pull/289#discussion_r1714845794
잘 읽어보았습니다..! 변경하신 이유를 일단 이해했어요

관련해서 조그만 걱정?이 있는데 일단 말씀드려보겠습니다!
`gcTime: 0`으로 설정하면 gcTime, staleTime 모두 0인 상태이기 때문에, 항상 새로운 프로필을 받아와야합니다.
그런데 이 상태라면 쿼리 캐싱이 무력화되는게 아닐까 싶습니다

더 좋은 방법이 있을 것 같아요 😈
쿼리 캐싱 관련해 [제가 참고한 글](https://velog.io/@tykim1227/react-query-%ED%8C%8C%EB%B3%B4%EA%B8%B0-%EC%BA%90%EC%8B%B1-%EB%9D%BC%EC%9D%B4%ED%94%84%EC%82%AC%EC%9D%B4%ED%81%B4)이 있어 공유드려봅니다!

2024-08-14 06:01 UTC, 0chil commented on src/hooks/queries/members.query.ts
세세한 테스트 아주 좋습니다!
https://github.com/snack-game/front/pull/289#discussion_r1716344435 확인 부탁드려요

2024-08-14 06:23 UTC, 0chil commented
디스코드 알림이 안가는 것 같아 멘션합니다 @nijuy

2024-08-14 06:35 UTC, nijuy commented on src/pages/user/components/ProfileSection.tsx
> +      newProfile = await changeGroupName.mutateAsync(newGroup.value || null);
옹. 확인했습니다!! 굿굿입니다
(그룹 가입 / 수정 / 탈퇴 잘 되는 점 확인했습니다~~!)

![group](https://github.com/user-attachments/assets/957298ae-29e0-4915-868d-5c27e2ad3677)

2024-08-14 07:55 UTC, nijuy commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
레퍼런스 공유 감사합니다 세심땡칠 

> `gcTime: 0`으로 설정하면 gcTime, staleTime 모두 0인 상태이기 때문에, 항상 새로운 프로필을 받아와야합니다.

불필요하게 네트워크 요청 수가 늘어날 거 같다는 우려로 이해했는데요!!

전후 모두 `staleTime: 0`이므로 `/user`에 접근할 때마다 항상 프로필을 받아오는 건 동일하지 않..나요?!
다만 새로운 프로필을 받아올 동안 보여줄 캐시 데이터가 있냐 없냐의 차이로 생각하고 이렇게 했었걸랑요

2024-08-14 09:50 UTC, 0chil commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
오우 고민을 정말 많이 해주셨네요. 그새 변경사항까지..!
뭔가 변경하라는 무언의 압박(?)은 아니었습니다 ㅋㅋㅋㅋㅋ

먼저 'staleTime: 0이므로 컴포넌트의 언마운트/마운트 시 결국 항상 새로 가져오지 않느냐?' 하는 의견 주셨는데요,
맞습니다!! 제가 생각이 짧았던 것 같아요.
요청을 보내느냐 안보내느냐? 는 gcTime에 의해 결정되는 것이 아니었네요!
그래도 `gcTime:0`이 getMemberProfile 쿼리를 사용하는 모든 곳에 영향을 미칠테니 `gcTime:0` 에 대해 고민은 한번 해봐야할 것 같아요.
---

그리고 제가 전달드리고 싶던 바는 SettingsPage.handleLogout에서 다음과 같은 쿼리를 사용하면 진정한 원인 해결이 되지 않을까하는 것이었습니다:
```ts
export const useLogout = () => {
  return useMutation({
    mutationFn: logOut,
    onSuccess: () =>
      queryClient.invalidateQueries({
        queryKey: [QUERY_KEY.USER_PROFILE],
      }),
  });
};
```
요건 어떻게 생각하시나요?

2024-08-14 09:52 UTC, 0chil commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
\+ 원래 로컬에서는 문제 재현이 안되나요..?

2024-08-14 09:57 UTC, 0chil commented on src/pages/user/components/UserInfo.tsx
>            <ProfileSection
fetch가 끝나기 전에 프로필이 렌더링 되어 캐시된 프로필이 유지된다고 이해해도 괜찮을까요?

2024-08-14 10:08 UTC, nijuy commented on src/pages/user/components/UserInfo.tsx
>            <ProfileSection
이그젝틀리입니다 아주 제 의도를 간파하셨습니다!!!!!

2024-08-14 10:33 UTC, 0chil approved these changes
제가 생각한 방법은 잘 되지 않네요 ㅠㅠ
`gcTime: 0` 혹은 `isFetching`으로 머지해주시면 감사드리겠습니다!
빠른 대응 감사드리고, 고생하셨습니다!

2024-08-14 10:43 UTC, nijuy commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
> 요건 어떻게 생각하시나요?

왜 제안한 방법 대신 다른 방법으로 해봤는지 제가 말씀을 안 드렸군요? 저의 생각은 8cm입니다.........
우선 `로그아웃 할 때 프로필 쿼리를 무효화 시키는 방법`에서는 `캐시 데이터가 전달된다`는 문제가 해결되지 않았고, 
현재 동작에서 달라지는 부분이 없다고 생각했기 때문입니다..!

1. 로그아웃을 성공하면 프로필 쿼리를 무효화시킨다
2. 프로필 쿼리가 다시 active 될 때, **(1)로 인해 유효하지 않은 쿼리가 됐으므로** 새 데이터를 가져온다

    ➡️ 쿼리가 active 된다 = `해당 쿼리를 사용하는 컴포넌트가 마운트 될 때`를 의미합니다. 즉, `/user`에 접근하는 시점입니다

    ➡️ 하지만 해당 쿼리의 `staleTime: 0`이므로 무효화하지 않아도 active 시점에 새 데이터를 가져오는 것은 동일하다...!!

3. 새 데이터를 가져오는 동안 캐시된 데이터가 스윽 `ProfileSection`으로....
 

안돼........ 장문의 코멘트를 쓰는 동안 이미 확인해보셨군요 다음부턴 재빠르게 쓰겠습니다

---

> 원래 로컬에서는 문제 재현이 안되나요..?

엇.
되어야........ 하는데..........
`계정 A 로그인` -> `로그아웃` -> `계정 B 로그인` -> `계정 B 프로필 수정 화면` 에서 문제 발견 가능합니다!

아니면 이 브랜치(fix/288-no-group)의 최신 버전에서는 문제가 해결된 상태라.. 재현이 안되는 게 맞긴 한데!!
develop에서도 안되나요? 식은땀 뻘뻘 나려고 한다

![재현](https://github.com/user-attachments/assets/0d89acd6-c34a-4634-9d78-dee0cc49ca63)

2024-08-14 10:47 UTC, nijuy commented
그렇다면.. isFetching으로 당첨 땅땅. 하겠습니다

> 그래도 gcTime:0이 getMemberProfile 쿼리를 사용하는 모든 곳에 영향을 미칠테니 고민은 한번 해봐야할 것 같아요.

제가 다른 부분에 대한 고민이 부족하기도 했고!!!!!!!

`ProfileSection`으로 캐시 데이터를 사용하지 않겠다는 의미는 isFetching에서 더 잘 드러나는 걱 같아서!!!

2024-08-14 10:47 UTC, merged

2024-08-14 12:10 UTC, 0chil commented on src/hooks/queries/members.query.ts
> +    gcTime: 0,
앗 장문의 커멘트를 써두셨군용
말씀해쥬신 과정 이해했습니다
근데 왜 한번 ProfileSection으로 들어간 데이터는 영영 바뀌지 못하는걸까요 ㅠㅠ
넘모 어려워서 다음에 탐구해보겠습니다🥲

그리구 재현이 안된건 추측하신 과정이 맞습니다 ^.^
CCTV 달아놓으셨나요