feat: 게임판 검증 API 적용
snack-game/front pull request #311
Opened 2024-10-15 10:34 UTC by nijuy

## 💻 개요

- 신규 피쳐인 척 옛날 피쳐 살리기
- #307

## 📋 변경 및 추가 사항

### 기존
- 게임판은 프론트에서 랜덤 생성한다
- 스트릭 제거 시 그 길이만큼 점수를 올리기 위해 점수 수정 API 요청을 보낸다

### 현재
- 게임판은 서버에서 보내주는 값을 사용한다
- 스트릭 제거 시

  - 일반 스트릭은 `cumulativeStreaks` 배열에 저장한다
  - 황금 스트릭은 지금까지 제거한 모든 스트릭을 넣어서 검증 API 요청을 보낸다 (새 판을 받아와야 해서)<br/><br/>

  > 일시정지와 게임 종료 시, 아직 검증되지 않은 스트릭이 있다면 검증 API 요청을 보낸 후 일시정지/종료합니다!

## 💬 To. 리뷰어

어제까지 한다고 해놓고. 전 거짓말쟁이입니다.

2024-10-16 05:51 UTC, 0chil commented
(오늘 리뷰예정)

2024-10-16 18:36 UTC, 0chil requested changes
길고 어려운 작업이었겠네요. 너무 고생 많으셨습니다.💯💯💯💯💯💯
![giphy-ezgif com-webp-to-gif-converter](https://github.com/user-attachments/assets/c9a2abf5-f3ba-4c21-b70a-20e66f40d706)
![5Sa](https://github.com/user-attachments/assets/97f3ad1f-d536-415b-ac6b-f49447de462f)

당장은 이 정도가 최선인 것 같고, 나중에 보수공사할 수 있는 부분들이 보여서 커멘트 남겨뒀어요.
TODO 같은걸로 표시해두고 같이 해결해나가면 좋겠습니다!

그리구 맘같아선 당장 머지하고 싶지만, 오류가 날 수 있는 부분(시간 관련) 때문에 먼저 수정 요청드립니다.

2024-10-16 18:36 UTC, 0chil commented on src/pages/games/SnackGame/game/snackGame/SnackGameAction.ts
>            this.snackGame.onSnackGameBoardReset?.();
좋은 구조는 아닌 것 같지만.. 당장은 최선인 것 같네요 👀
새로운 `SnackGameActions`을 만들어서 -> session을 외부(SnackgameBase)에서 수급할 수 있게 된다면?
좀 나아지지 않을까요? 자세한건 직접 만나서 얘기해봐요

2024-10-16 18:36 UTC, 0chil commented on src/pages/games/SnackGame/game/SnackGameBase.tsx
> +  let cumulativeStreaks: Streak[] = [];
변수명이 아주 적절하네요 ㄷㄷ 센스짱

2024-10-17 05:47 UTC, nijuy commented on src/pages/games/SnackGame/game/snackGame/SnackGameUtil.ts
> +      const currentType = board[r][c].golden ? 2 : 1;
저도 작업하면서 어. 황금이 1이었나 2였나......... 가물가물한 적이 종종 있어서 매우 동의합니더

2024-10-17 05:51 UTC, nijuy commented on src/pages/games/SnackGame/game/util/api.ts
> +  const { data } = await api.post(`/games/2/${sessionId}/streaks`, { streaks });
둘다 좋은 이름이라 293824시간 고민 끝에......... `SnackGameVerify` 타입도 있으니께 일관성을 위해 후자로 하겠습니다!!!!

2024-10-17 06:07 UTC, nijuy commented on src/pages/games/SnackGame/game/screen/GameScreen.ts
> +    this.snackGame.setup(snackGameConfig, board);
> (비꼬는거 아닙니다 😇)

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 아나 천사 이모지 웃기다

> 이게 맞는지 고민되진 않으셨나요? 

함수 내부를 수정하는 건 괜찮았는데 호출 순서 같은 거 조정하면서 종종 이래도 되나. 싶긴 했어요
바로 아래에서 짚어주신 `handleGameStart`............. 라덩가 ㅎㅎ^^..........

처음으로 게임 로직 손대려니까 죄금 겁나서 희수 오빠를 회사에서 납치해오고 싶었답니다

2024-10-17 07:04 UTC, nijuy commented on src/pages/games/SnackGame/game/snackGame/SnackGame.ts
> +  public onStreak?: (data: Snack[]) => Promise<SnackGameVerify | void>;
저 `void`가 있는 이유는 `handleStreak`의 리턴 타입 때문인데요!

```ts
  const handleStreak = async (streak: Streak, isGolden: boolean) => {
    cumulativeStreaks = [...cumulativeStreaks, streak];

    if (isGolden) {
      ...
      return result; // 황금 스트릭일 때만 값을 반환하고
    }
   // 일반 스트릭일 때는 undefined가 반환됨
  };
```

응답을 통합해도 `if(isGolden)` 조건문 내에서만 `SnackGameVerify` 타입인 게 보장되는 거라서
`handleStreak`의 리턴 타입이 `Promise<SnackGameVerify>` 으로 추론되지 않아요!

2024-10-17 07:26 UTC, nijuy commented on src/pages/games/SnackGame/game/screen/GameScreen.ts
>    }
자세한 설명 감사합니다 으아악
보드 정보 전달을 위해 `onPrepare`로 이사시켜 버렸는데..... `startPlaying()`을 보지 못한 저의 실수
땡칠없이못살아정말못살아

![SpongebobThumbsupGIF](https://github.com/user-attachments/assets/77abda0f-5828-4ea6-b88f-1a6c7404c29e)

2024-10-17 08:14 UTC, 0chil commented on src/pages/games/SnackGame/game/snackGame/SnackGame.ts
> +  public onStreak?: (data: Snack[]) => Promise<SnackGameVerify | void>;
아하 가 아니라!
return을 `if(isGolden)` 밖으로 빼도 마찬가지인가요❓
```ts
cumulativeStreaks = [...cumulativeStreaks, streak];

if (isGolden) {
  const result = await handleStreaksMove();
  if (result) session = result;
}
return session!;
```
이런식으로 말이죠 (session이 비어있는 경우는 일반적인 경우가 아니라 아예 예외상황이라서 `!` 사용했습니다)

이렇식으로 야금야금 해서~ 길게보았을 때 아래와 같은 코드가 되기를 기원합니다.. 🙇🏻
```ts
const handleStreak = async (streak: Streak) => { // <- isGolden 없어도 됨
  cumulativeStreaks = [...cumulativeStreaks, streak];

  if (streak.hasGoldenSnack) { // <- streak을 객체화해서, 황금 스낵이 있는지 확인하는 책임을 부여
    session = await handleStreaksMove(); // hasGoldenSnack === true 이므로 항상 Board가 반환됨 -> 확인 필요 X
  }
  // return 필요없음, SnackGame에서는 새 Board를 수급할 다른 방법이 구현됨.
};
```

2024-10-17 08:19 UTC, 0chil commented on src/pages/games/SnackGame/game/screen/GameScreen.ts
> +    this.snackGame.setup(snackGameConfig, board);
@dev-dong-su 소환술 가능할까요 ㅋㅋ

2024-10-17 08:25 UTC, 0chil approved these changes
고생 많으셨습니다!
게임 시간 관련한 변경사항 121로 하신 것 잘봤습니다 ㅋㅋㅋㅋ 🤣 👍🏻💯
제가 수도코드를 하나 커멘트 했는데 의견 한 번 주시고, 이번 PR은 머지하도록 할까요?

2024-10-17 08:25 UTC, 0chil commented on src/pages/games/SnackGame/game/screen/GameScreen.ts
아하 요렇게 해결하셨군요.
당장은 최선일 거 같습니다

2024-10-17 09:16 UTC, nijuy commented on src/pages/games/SnackGame/game/snackGame/SnackGame.ts
> +  public onStreak?: (data: Snack[]) => Promise<SnackGameVerify | void>;
> 아하 가 아니라!

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

제시해주신 코드 이해했습니다! 
비어있는 경우는 예외 상황이라 (정상 동작의 경우 handleGameStart에서 무조건 값이 들어가니까) `!` 사용한 점도요

서버 응답 통합하는 걸로 이해하고 void 멸종시키겠습니다 머지 부탁햐요 🤸‍♀️

---

> 이렇식으로 야금야금 해서~ 길게보았을 때 아래와 같은 코드가 되기를 기원합니다.. 🙇🏻

계속 session.board를 전달하고 전달하고 전달전ㄷㄹㄷ자전달하는 점이 좀... 그렇긴 하네요
이 방식으로 인해 게임 시작이 다 `onShow` -> `onPrepare`로 이동해야만 하기도 하고 🥲
보드를 수급할 다른 방법이 필요하다........... 이해 완료.............

2024-10-17 09:25 UTC, nijuy commented
> 제가 수도코드를 하나 커멘트 했는데 의견 한 번 주시고, 이번 PR은 머지하도록 할까요?

넹!!! 꼼칠리뷰는 받을 때마다 배워가는 게 129ㅕ3개네요
말씀하신 부분 수정해서 커밋했고, 이 PR은 머지한 뒤 주중에 TODO 관련해서 새 이슈 만들어 두겠십니더

2024-10-17 09:26 UTC, merged